real-brother-ssafy/eggorithm-study

wngud/week_03/BOJ_10026_적록색약/Main.java
wngud/week_03/BOJ_1012_유기농배추/Main.java
wngud/week_03/BOJ_11279_최대힙/Main.java
wngud/week_03/BOJ_11286_절대값힙/Main.java
wngud/week_03/BOJ_13565_침투/Main.java
wngud/week_03/BOJ_17086_아기상어2/Main.java
wngud/week_03/BOJ_1927_최소힙/Main.java
wngud/week_03/BOJ_21736_헌내기는친구가필요해/Main.java
wngud/week_03/BOJ_2468_안전영역/Main.java
wngud/week_03/BOJ_2583_영역구하기/Main.java
wngud/week_03/BOJ_4963_섬의개수/Main.java

JH_week_03_final

---

wngud/week_04/BOJ_1068_트리/Main.java
wngud/week_04/BOJ_11725_트리의부모찾기/Main.java
wngud/week_04/BOJ_1967_트리의지름/Main.java
wngud/week_04/BOJ_5639_이진검색트리/Main.java
wngud/week_04/BOJ_9372_상근이의여행/Main.java
wngud/week_04/BOJ_9934_완전이진트리/Main.java

JH_week04_completion

---

jaehyunKing/week_06/BOJ_11403_경로찾기/Main.java
jaehyunKing/week_06/BOJ_11724_연결요소의개수/Main.java
jaehyunKing/week_06/BOJ_15649_N과M1/Main.java
jaehyunKing/week_06/BOJ_1780_종이의개수/Main.java
jaehyunKing/week_06/BOJ_1992_쿼드트리/Main.java
jaehyunKing/week_06/BOJ_2606_바이러스/Main.java
jaehyunKing/week_06/BOJ_2606_바이러스/Main1.java
jaehyunKing/week_06/BOJ_2606_바이러스/Main2.java
jaehyunKing/week_07/BOJ_1074_Z/Main.java
jaehyunKing/week_07/BOJ_14889_스타트와링크/Main.java
jaehyunKing/week_07/BOJ_1629_곱셈/Main.java
jaehyunKing/week_07/BOJ_17070_파이프옮기기1/Main.java
jaehyunKing/week_07/BOJ_17471_게리맨더링/Main.java
jaehyunKing/week_07/BOJ_1939_중량제한/Main.java
jaehyunKing/week_07/BOJ_21610_마법사상어와비바라기/Main.java
jaehyunKing/week_07/BOJ_7576_토마토/Main.java

6주차 7주차 업로드

---

wngud/week_07/BOJ_ 1629_곱셈/Main.java
wngud/week_07/BOJ_1074_Z/Main.java
wngud/week_07/BOJ_14889_스타트와링크/Main.java
wngud/week_07/BOJ_17070_파이프옮기기1/Main.java
wngud/week_07/BOJ_17471_게리멘더링/Main.java
wngud/week_07/BOJ_21610_마법사상어와비바라기/Main.java
wngud/week_07/BOJ_7576_토마토/Main.java

JH_week07_complete

---

wngud/week_09/BOJ_13549_숨박꼭질3/Main.java
wngud/week_09/BOJ_14502_연구소/Main.java
wngud/week_09/BOJ_16236_아기상어/Main.java
wngud/week_09/BOJ_17144_미세먼지안녕!/Main.java
wngud/week_09/BOJ_1941_소문난칠공주/Main.java
wngud/week_09/BOJ_20055_컨베이어벨트위의로봇/Main.java

[Solved] week09

---

wngud/week_10/BOJ_1197_최소스패닝트리/Main.java
wngud/week_10/BOJ_12110_2048(Easy)/Main.java
wngud/week_10/BOJ_14503_로봇청소기/Main.java
wngud/week_10/BOJ_1504_특정한최단경로/Main.java
wngud/week_10/BOJ_16398_행성연결/Main.java
wngud/week_10/BOJ_17135_캐슬디펜스/Main.java
wngud/week_10/BOJ_17281_(야구)/Main.java
wngud/week_10/BOJ_1753_최단경로/Main.java

[Solved] week10

---

wngud/week_11/BOJ_1005_ACMCraft/Main.java
wngud/week_11/BOJ_15683_감시/Main.java
wngud/week_11/BOJ_20061_모노미노도미노2/Main.java
wngud/week_11/BOJ_23288_주사위굴리기/Main.java
wngud/week_11/BOJ_3109_빵집/Main.java

complete week11

---

jaehyunKing/week_12/BOJ_15686_치킨배달/Main.java
jaehyunKing/week_12/BOJ_16637_괄호추가하기/Main.java
jaehyunKing/week_12/BOJ_2636_치즈/Main.java
jaehyunKing/week_12/BOJ_2636_치즈/Main2.java
jaehyunKing/week_12/BOJ_9251_LCS/Main.java

11주차 4/6 해결완료

---

wngud/week_12/BOJ_15684_사다리조작/Main.java
wngud/week_12/BOJ_2565_전깃줄/Main.java
wngud/week_12/BOJ_9251_LCS/Main.java

week_12 완료..ㅠ

---

jaehyunKing/week_14/BOJ_17406_배열돌리기4/Main.java
jaehyunKing/week_14/BOJ_1987_알파벳/Main.java
jaehyunKing/week_14/BOJ_2110_공유기설치/Main.java
jaehyunKing/week_14/BOJ_2293_동전1/Main.java

PR: Week_14

---

jaehyunKing/week_15/BOJ_1339_단어수학/Main.java
jaehyunKing/week_15/BOJ_20056_마법사상어와파이어볼/Main.java
jaehyunKing/week_15/SWEA_14510_나무높이/Solution.java

PR: Week_15

---

wngud/week_17/BOJ_1389_케빈-베이컨의-6단계-법칙/Main.java
wngud/week_17/BOJ_2156_포도주-시식/Main.java
wngud/week_17/BOJ_2458_키-순서/Main.java
wngud/week_17/BOJ_2493_탑/Main.java
wngud/week_17/BOJ_5430_AC/Main.java
wngud/week_17/BOJ_9205_맥주-마시면서-걸어가기/Main.java
wngud/week_18/PGS_미로-탈출-명령어/Main.java
wngud/week_18/PGS_이모티콘-할인행사/Main.java
wngud/week_18/PGS_택배-배달과-수거하기/Main.java
wngud/week_18/PGS_표-병합/Main.java
wngud/week_18/PGS_표현-가능한-이진트리/Main.java
wngud/week_19/BOJ_11559_Puyo Puyo/Main.java
wngud/week_19/BOJ_1717_집합의 표현/Main.java
wngud/week_19/BOJ_4458_녹색 옷 입은 애가 젤다지/Main.java
wngud/week_20/PGS_양과 늑대/Main.java
wngud/week_20/PGS_양궁대회/Main.java
wngud/week_20/PGS_파괴되지 않은 건물/Main.java

week17_complete

---

jaehyunKing/week_17/BOJ_1389_케빈베이컨의6단계법칙/.gitignore
jaehyunKing/week_17/BOJ_1389_케빈베이컨의6단계법칙/Main.java
jaehyunKing/week_17/BOJ_2156_포도주시식/Main.java
jaehyunKing/week_17/BOJ_2458_키순서/Main.java
jaehyunKing/week_17/BOJ_2493_탑/Main.java
jaehyunKing/week_17/BOJ_5430_AC/Main.java
jaehyunKing/week_17/BOJ_9205_맥주마시면서걸어가기/Main.java
jaehyunKing/week_18/PGS_123떨어뜨리기/Solution.java
jaehyunKing/week_18/PGS_개인정보수집유효기간/Solution.java
jaehyunKing/week_18/PGS_미로탈출명령어/Solution.java
jaehyunKing/week_18/PGS_이모티콘할인행사/Solution.java
jaehyunKing/week_18/PGS_택배배달과수거기간/Solution.java
jaehyunKing/week_18/PGS_표현가능한이진트리/Solution.java

PR: Week_17

---

jaehyunKing/week_19/BOJ_11559_PuyoPuyo/Main.java
jaehyunKing/week_19/BOJ_2668_숫자고르기/Main.java
jaehyunKing/week_19/BOJ_4485_녹색옷입은애가젤다지/Main.java
jaehyunKing/week_20/PGS_양과늑대/Solution.java
jaehyunKing/week_20/PGS_파괴되지않은건물/Solution.java
jaehyunKing/week_21/BOJ_1202_보석도둑/Main.java
jaehyunKing/week_21/BOJ_1520_내리막길/Main.java
jaehyunKing/week_21/BOJ_22255_호석사우루스/Main.java
jaehyunKing/week_21/BOJ_2457_공주님의정원/Main.java

PR: Week_21

---

wngud/week_21/BOJ_2457_공주님의 정원/Main.java
wngud/week_22/BOJ_1991_트리 순회/Main.java
wngud/week_22/BOJ_3584_가장 가까운 공통 조상/Main.java
wngud/week_22/PGS_광고 삽입/Main.java
wngud/week_22/PGS_합승 택시 요금/Main.java

PR: Week_22

---

wngud/week_23/BOJ_14267_회사 문화 1/Main.java
wngud/week_23/BOJ_1937_욕심쟁이 판다/Main.java
wngud/week_23/BOJ_21276_계보 복원가 호석/Main.java
wngud/week_23/BOJ_3109_빵집/Main.java

PR: week23

---

jaehyunKing/week_24/BOJ_1987_알파벳/Main.java
jaehyunKing/week_24/BOJ_21275_폰호석만/Main.java
jaehyunKing/week_24/BOJ_2636_치즈/Main.java
jaehyunKing/week_24/BOJ_3055_탈출/Main.java
jaehyunKing/week_24/PGS_k진수에서_소수_개수_구하기/Solution.java
jaehyunKing/week_24/PGS_괄호_변환/Solution.java
jaehyunKing/week_24/PGS_순위_검색/Solution.java
jaehyunKing/week_24/PGS_주차_요금_계산/Solution.java

PR: Week_24

---

wngud/week_26/PGS_블록 이동하기/Main.java

PR: week_26

---

.idea/.gitignore
.idea/eggolism-study.iml
.idea/misc.xml
.idea/modules.xml
.idea/vcs.xml
wngud/week_27/BOJ_14500_테트로미노/Main.java
wngud/week_27/BOJ_2170_선긋기/Main.java

PR: Week_27

---

.idea/.gitignore
.idea/eggolism-study.iml
.idea/misc.xml
.idea/modules.xml
.idea/vcs.xml
wngud/week_28/PGS_길 찾기 게임/Main.java

PR: Week_28

---

wngud/week_29/PGS_두 큐 합 같게 만들기/Main.java
wngud/week_29/PGS_문자열 압축/Main.java
wngud/week_29/PGS_오픈채팅방/Main.java
wngud/week_29/PGS_프렌즈4블록/Main.java
wngud/week_29/PGS_후보키/Main.java

PR: Week_29
